package com.kopin.pupil.pagerenderer;

import android.content.Context;
import android.support.v4.view.ViewCompat;
import com.kopin.pupil.ui.elements.BaseElement;
import com.kopin.pupil.ui.elements.BatteryElement;
import com.kopin.pupil.ui.elements.BoxElement;
import com.kopin.pupil.ui.elements.DictationElement;
import com.kopin.pupil.ui.elements.ImageElement;
import com.kopin.pupil.ui.elements.MicElement;
import com.kopin.pupil.ui.elements.ProgressElement;
import com.kopin.pupil.ui.elements.SignalElement;
import com.kopin.pupil.ui.elements.SingleLineTextElement;
import com.kopin.pupil.ui.elements.TextElement;

/* JADX INFO: loaded from: classes25.dex */
public class StandardTheme extends Theme {
    public static final int BLUE_THEME_COLOR = -11623487;
    public static final int GREEN_THEME_COLOR = -10240624;
    public static final int GREY_THEME_COLOR = -8092283;
    public static final int ORANGE_THEME_COLOR = -2647225;
    public static final int PURPULE_THEME_COLOR = -6262062;
    public static final int RED_THEME_COLOR = -4495275;

    public StandardTheme(int themeColor, int borderThemeColor, Context context) {
        super(context, "Roboto");
        ThemeElement defaultElement = new ThemeElement();
        defaultElement.color = ViewCompat.MEASURED_STATE_MASK;
        defaultElement.backColor = -1;
        defaultElement.borderColor = 0;
        defaultElement.borderThickness = 0;
        defaultElement.activeColor = 0;
        defaultElement.inactiveColor = 0;
        defaultElement.textSize = 0;
        defaultElement.textStyle = 0;
        defaultElement.element = BaseElement.class;
        ThemeElement boxElement = new ThemeElement();
        boxElement.color = 0;
        boxElement.backColor = -1;
        boxElement.borderColor = 0;
        boxElement.borderThickness = 0;
        boxElement.activeColor = 0;
        boxElement.inactiveColor = 0;
        boxElement.textSize = 0;
        boxElement.textStyle = 0;
        boxElement.element = BoxElement.class;
        ThemeElement textElement = new ThemeElement();
        textElement.color = ViewCompat.MEASURED_STATE_MASK;
        textElement.backColor = 0;
        textElement.borderColor = 0;
        textElement.borderThickness = 0;
        textElement.activeColor = 0;
        textElement.inactiveColor = 0;
        textElement.textSize = 0;
        textElement.textStyle = 0;
        textElement.element = SingleLineTextElement.class;
        ThemeElement multiTextElement = new ThemeElement();
        multiTextElement.color = ViewCompat.MEASURED_STATE_MASK;
        multiTextElement.backColor = 0;
        multiTextElement.borderColor = 0;
        multiTextElement.borderThickness = 0;
        multiTextElement.activeColor = 0;
        multiTextElement.inactiveColor = 0;
        multiTextElement.textSize = 0;
        multiTextElement.textStyle = 0;
        multiTextElement.element = TextElement.class;
        ThemeElement imageElement = new ThemeElement();
        imageElement.color = -1;
        imageElement.backColor = 0;
        imageElement.borderColor = 0;
        imageElement.borderThickness = 0;
        imageElement.activeColor = 0;
        imageElement.inactiveColor = 0;
        imageElement.textSize = 0;
        imageElement.textStyle = 0;
        imageElement.element = ImageElement.class;
        ThemeElement dictationElement = new ThemeElement();
        dictationElement.color = -3815995;
        dictationElement.backColor = -2105377;
        dictationElement.borderColor = -3355444;
        dictationElement.borderThickness = 2;
        dictationElement.activeColor = -10770751;
        dictationElement.inactiveColor = -8538549;
        dictationElement.textSize = 0;
        dictationElement.textStyle = 0;
        dictationElement.element = DictationElement.class;
        ThemeElement batteryElement = new ThemeElement();
        batteryElement.color = 0;
        batteryElement.backColor = 0;
        batteryElement.borderColor = 0;
        batteryElement.borderThickness = 0;
        batteryElement.activeColor = -1;
        batteryElement.inactiveColor = 872415231;
        batteryElement.textSize = 0;
        batteryElement.textStyle = 0;
        batteryElement.element = BatteryElement.class;
        ThemeElement signalElement = new ThemeElement();
        signalElement.color = -1;
        signalElement.backColor = 0;
        signalElement.borderColor = 0;
        signalElement.borderThickness = 0;
        signalElement.activeColor = 0;
        signalElement.inactiveColor = 0;
        signalElement.textSize = 0;
        signalElement.textStyle = 0;
        signalElement.element = SignalElement.class;
        ThemeElement micElement = new ThemeElement();
        micElement.color = 0;
        micElement.backColor = 0;
        micElement.borderColor = 0;
        micElement.borderThickness = 0;
        micElement.activeColor = themeColor;
        micElement.inactiveColor = -3947581;
        micElement.textSize = 0;
        micElement.textStyle = 0;
        micElement.element = MicElement.class;
        ThemeElement progressElement = new ThemeElement();
        progressElement.color = 0;
        progressElement.backColor = 0;
        progressElement.borderColor = 0;
        progressElement.borderThickness = 0;
        progressElement.activeColor = themeColor;
        progressElement.inactiveColor = -3947581;
        progressElement.textSize = 0;
        progressElement.textStyle = 0;
        progressElement.element = ProgressElement.class;
        addTheme(defaultElement, boxElement, textElement, multiTextElement, imageElement, dictationElement, batteryElement, signalElement, micElement, progressElement);
        this.mTextSizes.put("small", 27);
        this.mTextSizes.put(Theme.TEXT_SIZE_DEFAULT, 32);
        this.mTextSizes.put("large", 60);
        this.mColors.put("default_font", Integer.valueOf(ViewCompat.MEASURED_STATE_MASK));
        this.mColors.put(Theme.COLOR_ASR_FONT, -9671572);
        this.mColors.put(Theme.COLOR_CONTRAST_FONT, -1);
        this.mColors.put(Theme.COLOR_SUBTITLE_FONT, -11053225);
        this.mColors.put(Theme.COLOR_THEME, Integer.valueOf(themeColor));
        this.mColors.put(Theme.COLOR_THEME_DARK, -13593415);
        this.mColors.put(Theme.COLOR_THEME_BORDER, Integer.valueOf(borderThemeColor));
        this.mColors.put("positive", -12944640);
        this.mColors.put("negative", -8454131);
        this.mColors.put("call_in", Integer.valueOf(GREEN_THEME_COLOR));
        this.mColors.put("call_dialing", -8750470);
        this.mColors.put("call_ended", Integer.valueOf(RED_THEME_COLOR));
    }
}
